# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_url',
            field=models.CharField(default='error', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Location'),
        ),
    ]
