# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20170512_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Add last name', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Add last name', max_length=30),
        ),
    ]
