# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20170513_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
