# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-21 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20170513_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='insert announcement here', max_length=100)),
            ],
        ),
    ]
