# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_start_end_times',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
            preserve_default=False,
        ),
    ]
