# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-21 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20180721_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show_outside_of_set_times',
            field=models.BooleanField(default=False),
        ),
    ]
