# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_announcement_show_outside_of_set_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='end_time',
            field=models.DateField(verbose_name='End Day'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_time',
            field=models.DateField(verbose_name='Start Day'),
        ),
    ]
