# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
