# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20180723_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_time_description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
