# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_meeting_time_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_this_event',
            field=models.BooleanField(default=True),
        ),
    ]
