# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-23 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_show_this_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='class_size',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
